env:
  browser: true
  es2021: true
  node: true

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module

plugins:
  - react
  - react-hooks

settings:
  react:
    version: detect

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier

rules:
  react/prop-types: off
